/// 色名辞書。選んだ色の「最寄りの名前」をランドマークとして示すために使う。
///
/// - JIS 慣用色名 (JIS Z 8102:2001 系、267色)
/// - CSS 色名 (148色)
library;

enum NamedColorSource { jis, css }

class NamedColor {
  const NamedColor(this.name, this.reading, this.rgb, this.source);

  final String name;

  /// よみ (JIS) または英名そのまま (CSS)。
  final String reading;

  /// 0xRRGGBB
  final int rgb;

  final NamedColorSource source;

  int get r => (rgb >> 16) & 0xFF;
  int get g => (rgb >> 8) & 0xFF;
  int get b => rgb & 0xFF;
}

const namedColors = <NamedColor>[
  NamedColor('白', 'しろ', 0xF1F1F1, NamedColorSource.jis),
  NamedColor('銀鼠', 'ぎんねず', 0xA0A0A0, NamedColorSource.jis),
  NamedColor('鼠色', 'ねずみいろ', 0x868686, NamedColorSource.jis),
  NamedColor('灰色', 'はいいろ', 0x797979, NamedColorSource.jis),
  NamedColor('墨', 'すみ', 0x313131, NamedColorSource.jis),
  NamedColor('黒', 'くろ', 0x262626, NamedColorSource.jis),
  NamedColor('鉄黒', 'てつぐろ', 0x262626, NamedColorSource.jis),
  NamedColor('ホワイト', 'white', 0xF1F1F1, NamedColorSource.jis),
  NamedColor('スノーホワイト', 'snow white', 0xF1F1F1, NamedColorSource.jis),
  NamedColor('パールグレイ', 'pearl gray', 0xADADAD, NamedColorSource.jis),
  NamedColor('シルバーグレイ', 'silver gray', 0xA0A0A0, NamedColorSource.jis),
  NamedColor('アッシュグレイ', 'ash grey', 0x939393, NamedColorSource.jis),
  NamedColor('グレイ', 'gray/grey', 0x797979, NamedColorSource.jis),
  NamedColor('ランプブラック', 'lamp black', 0x1C1C1C, NamedColorSource.jis),
  NamedColor('ブラック', 'black', 0x1C1C1C, NamedColorSource.jis),
  NamedColor('朱色', 'しゅいろ/しゅしょく', 0xED514E, NamedColorSource.jis),
  NamedColor('バーミリオン', 'vermilion/vermillion', 0xED514E, NamedColorSource.jis),
  NamedColor('紅樺色', 'べにかばいろ', 0xA14641, NamedColorSource.jis),
  NamedColor('茶鼠', 'ちゃねずみ', 0x9F9190, NamedColorSource.jis),
  NamedColor('紅緋', 'べにひ', 0xEE5145, NamedColorSource.jis),
  NamedColor('スカーレット', 'scarlet', 0xDE4335, NamedColorSource.jis),
  NamedColor('生成色', 'きなりいろ', 0xF0E2E0, NamedColorSource.jis),
  NamedColor('鉛丹色', 'えんたんいろ', 0xD3503C, NamedColorSource.jis),
  NamedColor('紅海老茶', 'べにえびちゃ', 0x703B32, NamedColorSource.jis),
  NamedColor('テラコッタ', 'terracotta', 0xAC5647, NamedColorSource.jis),
  NamedColor('小豆色', 'あずきいろ', 0x946259, NamedColorSource.jis),
  NamedColor('鳶色', 'とびいろ', 0x7D483E, NamedColorSource.jis),
  NamedColor('サーモンピンク', 'salmon pink', 0xFFA594, NamedColorSource.jis),
  NamedColor('シェルピンク', 'shell pink', 0xFBCCC3, NamedColorSource.jis),
  NamedColor('弁柄色', 'べんがらいろ', 0x8A4031, NamedColorSource.jis),
  NamedColor('海老茶', 'えびちゃ', 0x6D3D33, NamedColorSource.jis),
  NamedColor('ネールピンク', 'nail pink', 0xF1BEB1, NamedColorSource.jis),
  NamedColor('金赤', 'きんあか', 0xED542A, NamedColorSource.jis),
  NamedColor('赤錆色', 'あかさびいろ', 0x923A21, NamedColorSource.jis),
  NamedColor('赤茶', 'あかちゃ', 0xB15237, NamedColorSource.jis),
  NamedColor('チョコレート', 'chocolate', 0x52372F, NamedColorSource.jis),
  NamedColor('肉桂色', 'にっけいいろ', 0xB97761, NamedColorSource.jis),
  NamedColor('錆色', 'さびいろ', 0x664134, NamedColorSource.jis),
  NamedColor('黄丹', 'おうに', 0xEF6D3E, NamedColorSource.jis),
  NamedColor('バーントシェンナ', 'burnt sienna', 0xA8593C, NamedColorSource.jis),
  NamedColor('キャロットオレンジ', 'carrot orange', 0xCC572C, NamedColorSource.jis),
  NamedColor('煉瓦色', 'れんがいろ', 0x974E33, NamedColorSource.jis),
  NamedColor('柿色', 'かきいろ', 0xE06030, NamedColorSource.jis),
  NamedColor('黒茶', 'くろちゃ', 0x3E2E28, NamedColorSource.jis),
  NamedColor('チャイニーズレッド', 'Chinese red', 0xFF5D20, NamedColorSource.jis),
  NamedColor('赤橙色', 'あかだいだい', 0xED551B, NamedColorSource.jis),
  NamedColor('樺色', 'かばいろ', 0xBD4A1D, NamedColorSource.jis),
  NamedColor('ピーチ', 'peach', 0xEBC0AF, NamedColorSource.jis),
  NamedColor('檜皮色', 'ひわだいろ', 0x8A604F, NamedColorSource.jis),
  NamedColor('栗色', 'くりいろ', 0x754C38, NamedColorSource.jis),
  NamedColor('ココアブラウン', 'cocoa brown', 0x754C38, NamedColorSource.jis),
  NamedColor('代赭', 'たいしゃ', 0xBA6432, NamedColorSource.jis),
  NamedColor('肌色', 'はだいろ', 0xF4BE9B, NamedColorSource.jis),
  NamedColor('駱駝色', 'らくだいろ', 0xB67A52, NamedColorSource.jis),
  NamedColor('象牙色', 'ぞうげいろ', 0xE3D4CA, NamedColorSource.jis),
  NamedColor('アイボリー', 'ivory', 0xE3D4CA, NamedColorSource.jis),
  NamedColor('焦茶', 'こげちゃ', 0x594639, NamedColorSource.jis),
  NamedColor('灰茶', 'はいちゃ', 0x866955, NamedColorSource.jis),
  NamedColor('黄赤', 'きあか', 0xE45E00, NamedColorSource.jis),
  NamedColor('黄茶', 'きちゃ', 0xBB6421, NamedColorSource.jis),
  NamedColor('ローシェンナ', 'raw sienna', 0xBB6421, NamedColorSource.jis),
  NamedColor('ブラウン', 'brown', 0x734E31, NamedColorSource.jis),
  NamedColor('杏色', 'あんずいろ', 0xDDA273, NamedColorSource.jis),
  NamedColor('アプリコット', 'apricot', 0xDDA273, NamedColorSource.jis),
  NamedColor('エクルベイジュ', 'ecru beige', 0xF8CFAE, NamedColorSource.jis),
  NamedColor('茶色', 'ちゃいろ', 0x734E30, NamedColorSource.jis),
  NamedColor('柑子色', 'こうじいろ', 0xFFA75E, NamedColorSource.jis),
  NamedColor('タン', 'tan', 0xA56F3F, NamedColorSource.jis),
  NamedColor('コルク', 'cork', 0xA58161, NamedColorSource.jis),
  NamedColor('褐色', 'かっしょく', 0x763900, NamedColorSource.jis),
  NamedColor('朽葉色', 'くちはいろ', 0x897868, NamedColorSource.jis),
  NamedColor('ベージュ', 'beige', 0xC1AB96, NamedColorSource.jis),
  NamedColor('橙色', 'だいだいいろ', 0xFD7E00, NamedColorSource.jis),
  NamedColor('オレンジ', 'orange', 0xFD7E00, NamedColorSource.jis),
  NamedColor('煤竹色', 'すすたけいろ', 0x605448, NamedColorSource.jis),
  NamedColor('バフ', 'buff', 0xC5996D, NamedColorSource.jis),
  NamedColor('小麦色', 'こむぎいろ', 0xD9A46D, NamedColorSource.jis),
  NamedColor('蜜柑色', 'みかんいろ', 0xFA8000, NamedColorSource.jis),
  NamedColor('砂色', 'すないろ', 0xC9B9A8, NamedColorSource.jis),
  NamedColor('ゴールデンイエロー', 'golden yellow', 0xF39A38, NamedColorSource.jis),
  NamedColor('土色', 'つちいろ', 0xA96E2D, NamedColorSource.jis),
  NamedColor('アンバー', 'amber', 0xB37D40, NamedColorSource.jis),
  NamedColor('セピア', 'sepia', 0x4A3B2A, NamedColorSource.jis),
  NamedColor('マンダリンオレンジ', 'mandarin orange', 0xFD951E, NamedColorSource.jis),
  NamedColor('ブロンズ', 'bronze', 0x815A2B, NamedColorSource.jis),
  NamedColor('卵色', 'たまごいろ', 0xFABE6F, NamedColorSource.jis),
  NamedColor('バーントアンバー', 'burnt umber', 0x5B462A, NamedColorSource.jis),
  NamedColor('琥珀色', 'こはくいろ', 0xC67400, NamedColorSource.jis),
  NamedColor('黄土色', 'おうどいろ', 0xC18A39, NamedColorSource.jis),
  NamedColor('イエローオーカー', 'yellow ocher', 0xC18A39, NamedColorSource.jis),
  NamedColor('レグホーン', 'leghorn', 0xE1C59B, NamedColorSource.jis),
  NamedColor('金茶', 'きんちゃ', 0xC47600, NamedColorSource.jis),
  NamedColor('カーキー', 'Khaki', 0x9A753A, NamedColorSource.jis),
  NamedColor('ブロンド', 'blond/blonde', 0xE3B466, NamedColorSource.jis),
  NamedColor('マリーゴールド', 'marigold', 0xFFA000, NamedColorSource.jis),
  NamedColor('ネープルスイエロー', 'Naples yellow', 0xF2C26B, NamedColorSource.jis),
  NamedColor('山吹色', 'やまぶきいろ', 0xFFA500, NamedColorSource.jis),
  NamedColor('芥子色', 'からしいろ', 0xCDA966, NamedColorSource.jis),
  NamedColor('クリームイエロー', 'cream yellow', 0xE8D5AF, NamedColorSource.jis),
  NamedColor('ローアンバー', 'raw umber', 0x7F5C13, NamedColorSource.jis),
  NamedColor('鬱金色', 'うこんいろ', 0xFCAC00, NamedColorSource.jis),
  NamedColor('向日葵色', 'ひまわりいろ', 0xFFB500, NamedColorSource.jis),
  NamedColor('鶯茶', 'うぐいすいろ', 0x70613A, NamedColorSource.jis),
  NamedColor('クロムイエロー', 'chrome yellow', 0xFFBC00, NamedColorSource.jis),
  NamedColor('黄色', 'きいろ', 0xFFBE00, NamedColorSource.jis),
  NamedColor('蒲公英色', 'たんぽぽいろ', 0xFFBE00, NamedColorSource.jis),
  NamedColor('オリーブドラブ', 'olive drab', 0x68624E, NamedColorSource.jis),
  NamedColor('刈安色', 'かりやすいろ', 0xEED67E, NamedColorSource.jis),
  NamedColor('カナリヤ', 'canary yellow', 0xF7D54E, NamedColorSource.jis),
  NamedColor('イエロー', 'yellow', 0xFFCC00, NamedColorSource.jis),
  NamedColor('ジョンブリアン', 'jaune brillant', 0xFFCC00, NamedColorSource.jis),
  NamedColor('中黄', 'ちゅうき', 0xFAD43A, NamedColorSource.jis),
  NamedColor('オリーブ', 'olive', 0x605627, NamedColorSource.jis),
  NamedColor('レモンイエロー', 'lemon yellow', 0xE8C800, NamedColorSource.jis),
  NamedColor('海松色', 'みる', 0x736F55, NamedColorSource.jis),
  NamedColor('黄蘗色', 'きはだいろ', 0xD9CB65, NamedColorSource.jis),
  NamedColor('鶸色', 'ひわ', 0xC2C05C, NamedColorSource.jis),
  NamedColor('鶯色', 'うぐいすいろ', 0x71714A, NamedColorSource.jis),
  NamedColor('抹茶色', 'まっちゃいろ', 0xBDBF92, NamedColorSource.jis),
  NamedColor('オリーブグリーン', 'olive green', 0x565838, NamedColorSource.jis),
  NamedColor('黄緑', 'きみどり/おうりょく', 0xB9C42F, NamedColorSource.jis),
  NamedColor('苔色', 'こけいろ', 0x7A7F46, NamedColorSource.jis),
  NamedColor('若草色', 'わかくさいろ', 0xA9B735, NamedColorSource.jis),
  NamedColor('グラスグリーン', 'grass green', 0x737C3E, NamedColorSource.jis),
  NamedColor('萌黄', 'もえぎ', 0x96AA3D, NamedColorSource.jis),
  NamedColor('シャトルーズグリーン', 'chartreuse green', 0xBDD458, NamedColorSource.jis),
  NamedColor('草色', 'くさいろ', 0x72814B, NamedColorSource.jis),
  NamedColor('リーフグリーン', 'leaf green', 0x879D4E, NamedColorSource.jis),
  NamedColor('シーグリーン', 'sea green', 0x9AB961, NamedColorSource.jis),
  NamedColor('若葉色', 'わかばいろ', 0xAFC297, NamedColorSource.jis),
  NamedColor('アイビーグリーン', 'ivy green', 0x516A39, NamedColorSource.jis),
  NamedColor('松葉色', 'まつばいろ', 0x6E815C, NamedColorSource.jis),
  NamedColor('アップルグリーン', 'apple green', 0xB0D3A8, NamedColorSource.jis),
  NamedColor('ミントグリーン', 'mint green', 0x81CC91, NamedColorSource.jis),
  NamedColor('緑', 'みどり', 0x4DB56A, NamedColorSource.jis),
  NamedColor('白緑', 'びゃくりょく', 0xCADBCF, NamedColorSource.jis),
  NamedColor('常磐色', 'ときわいろ', 0x357C4C, NamedColorSource.jis),
  NamedColor('グリーン', 'green', 0x2A9B50, NamedColorSource.jis),
  NamedColor('千歳緑', 'ちとせみどり', 0x4A6956, NamedColorSource.jis),
  NamedColor('緑青色', 'ろくしょういろ', 0x5F836D, NamedColorSource.jis),
  NamedColor('コバルトグリーン', 'cobalt green', 0x5DC288, NamedColorSource.jis),
  NamedColor('エメラルドグリーン', 'emerald green', 0x4DA573, NamedColorSource.jis),
  NamedColor('利休鼠', 'りきゅうねずみ', 0x787C7A, NamedColorSource.jis),
  NamedColor('ボトルグリーン', 'bottle green', 0x264435, NamedColorSource.jis),
  NamedColor('フォレストグリーン', 'forest green', 0x3E795C, NamedColorSource.jis),
  NamedColor('マラカイトグリーン', 'malachite green', 0x008047, NamedColorSource.jis),
  NamedColor('深緑', 'ふかみどり/しんりょく', 0x005731, NamedColorSource.jis),
  NamedColor('萌葱色', 'もえぎいろ', 0x15543B, NamedColorSource.jis),
  NamedColor('若竹色', 'わかたけいろ', 0x49A581, NamedColorSource.jis),
  NamedColor('青磁色', 'せいじいろ', 0x80AA9F, NamedColorSource.jis),
  NamedColor('ビリジアン', 'viridian', 0x156F5C, NamedColorSource.jis),
  NamedColor('ビリヤードグリーン', 'billiard green', 0x004840, NamedColorSource.jis),
  NamedColor('鉄色', 'てついろ', 0x244344, NamedColorSource.jis),
  NamedColor('青竹色', 'あおたけいろ', 0x7AAAAC, NamedColorSource.jis),
  NamedColor('ピーコックグリーン', 'peacock green', 0x007F91, NamedColorSource.jis),
  NamedColor('青緑', 'あおみどり', 0x0090A8, NamedColorSource.jis),
  NamedColor('ピーコックブルー', 'peacock blue', 0x00708B, NamedColorSource.jis),
  NamedColor('浅葱色', 'あさぎいろ', 0x0087AA, NamedColorSource.jis),
  NamedColor('ナイルブルー', 'Nile blue', 0x5190A4, NamedColorSource.jis),
  NamedColor('納戸色', 'なんどいろ', 0x166A88, NamedColorSource.jis),
  NamedColor('錆浅葱', 'さびあさぎ', 0x6C8D9B, NamedColorSource.jis),
  NamedColor('新橋色', 'しんばしいろ', 0x69AAC6, NamedColorSource.jis),
  NamedColor('マリンブルー', 'marine blue', 0x005175, NamedColorSource.jis),
  NamedColor('ターコイズブルー', 'turquoise blue', 0x399ECC, NamedColorSource.jis),
  NamedColor('シアン', 'cyan', 0x219DDD, NamedColorSource.jis),
  NamedColor('白群', 'びゃくぐん', 0x84B5CF, NamedColorSource.jis),
  NamedColor('水浅葱', 'みずあさぎ', 0x7A99AA, NamedColorSource.jis),
  NamedColor('セルリアンブルー', 'cerulean blue', 0x0B74AF, NamedColorSource.jis),
  NamedColor('瓶覗', 'かめのぞき', 0x8CB4CE, NamedColorSource.jis),
  NamedColor('水色', 'みずいろ', 0xA9CEEC, NamedColorSource.jis),
  NamedColor('青', 'あお', 0x0067C0, NamedColorSource.jis),
  NamedColor('ホリゾンブルー', 'horizon blue', 0x91B2D2, NamedColorSource.jis),
  NamedColor('藍鼠', 'あいねず', 0x5E7184, NamedColorSource.jis),
  NamedColor('空色', 'そらいろ', 0x95C0EC, NamedColorSource.jis),
  NamedColor('スカイブルー', 'sky blue', 0x95C0EC, NamedColorSource.jis),
  NamedColor('ミッドナイトブルー', 'midnight blue', 0x00152D, NamedColorSource.jis),
  NamedColor('ブルー', 'blue', 0x3170B9, NamedColorSource.jis),
  NamedColor('コバルトブルー', 'cobalt blue', 0x2863AB, NamedColorSource.jis),
  NamedColor('露草色', 'つゆくさいろ', 0x3D7CCE, NamedColorSource.jis),
  NamedColor('藍色', 'あいいろ', 0x2E4B71, NamedColorSource.jis),
  NamedColor('サックスブルー', 'saxeblue', 0x627DA1, NamedColorSource.jis),
  NamedColor('縹色', 'はんだいろ', 0x3C639B, NamedColorSource.jis),
  NamedColor('濃藍', 'こいあい', 0x20324E, NamedColorSource.jis),
  NamedColor('ベビーブルー', 'baby blue', 0xABBDDA, NamedColorSource.jis),
  NamedColor('勿忘草色', 'わすれなぐさいろ', 0x92AFE4, NamedColorSource.jis),
  NamedColor('紺青', 'こんじょう', 0x3D496B, NamedColorSource.jis),
  NamedColor('アイアンブルー', 'iron blue', 0x3D496B, NamedColorSource.jis),
  NamedColor('プルシャンブルー', 'Prussian Blue', 0x3D496B, NamedColorSource.jis),
  NamedColor('瑠璃色', 'るりいろ', 0x3451A4, NamedColorSource.jis),
  NamedColor('瑠璃紺', 'るりこん', 0x324784, NamedColorSource.jis),
  NamedColor('ヒヤシンス', 'hyacinth', 0x7586BB, NamedColorSource.jis),
  NamedColor('紺色', 'こんいろ', 0x333C5E, NamedColorSource.jis),
  NamedColor('ネービーブルー', 'navyblue', 0x333C5E, NamedColorSource.jis),
  NamedColor('杜若色', 'かきつばたいろ', 0x4C5DAB, NamedColorSource.jis),
  NamedColor('群青色', 'ぐんじょういろ', 0x414FA3, NamedColorSource.jis),
  NamedColor('ウルトラマリンブルー', 'ultramarine blue', 0x414FA3, NamedColorSource.jis),
  NamedColor('オリエンタルブルー', 'oriental blue', 0x37438F, NamedColorSource.jis),
  NamedColor('勝色', 'かちいろ', 0x383C57, NamedColorSource.jis),
  NamedColor('鉄紺', 'てつこん', 0x232538, NamedColorSource.jis),
  NamedColor('鉛色', 'なまりいろ', 0x797A88, NamedColorSource.jis),
  NamedColor('藤納戸', 'ふじなんど', 0x6869A8, NamedColorSource.jis),
  NamedColor('紺藍', 'こんあい', 0x35357D, NamedColorSource.jis),
  NamedColor('スカイグレイ', 'sky gray', 0xBABAC6, NamedColorSource.jis),
  NamedColor('桔梗色', 'ききょういろ', 0x4A49AD, NamedColorSource.jis),
  NamedColor('藤色', 'ふじいろ', 0xA09BD8, NamedColorSource.jis),
  NamedColor('ウィスタリア', 'wistaria', 0x776ED2, NamedColorSource.jis),
  NamedColor('スレートグレイ', 'slate gray', 0x56555E, NamedColorSource.jis),
  NamedColor('藤紫', 'ふじむらさき', 0x948BDB, NamedColorSource.jis),
  NamedColor('パンジー', 'pansy', 0x40317E, NamedColorSource.jis),
  NamedColor('ヘリオトロープ', 'heliotrope', 0x836DC5, NamedColorSource.jis),
  NamedColor('鳩羽色', 'はとばいろ', 0x675D7E, NamedColorSource.jis),
  NamedColor('菫色', 'すみれいろ', 0x6D52AB, NamedColorSource.jis),
  NamedColor('バイオレット', 'violet', 0x6D52AB, NamedColorSource.jis),
  NamedColor('青紫', 'あおむらさき', 0x704CBC, NamedColorSource.jis),
  NamedColor('江戸紫', 'えどむらさき', 0x5F4C86, NamedColorSource.jis),
  NamedColor('菖蒲色', 'しょうぶいろ', 0x7051AA, NamedColorSource.jis),
  NamedColor('モーブ', 'mauve', 0x835FA8, NamedColorSource.jis),
  NamedColor('ラベンダー', 'lavender', 0x9E8EAE, NamedColorSource.jis),
  NamedColor('チャコールグレイ', 'charcoal gray', 0x4E4854, NamedColorSource.jis),
  NamedColor('スチールグレイ', 'steel gray', 0x736C79, NamedColorSource.jis),
  NamedColor('ライラック', 'lilac', 0xC2A2DA, NamedColorSource.jis),
  NamedColor('茄子紺', 'なすこん', 0x47384F, NamedColorSource.jis),
  NamedColor('古代紫', 'こだいむらさき', 0x775686, NamedColorSource.jis),
  NamedColor('紫', 'むらさき', 0xA260BF, NamedColorSource.jis),
  NamedColor('パープル', 'purple', 0xA260BF, NamedColorSource.jis),
  NamedColor('オーキッド', 'orchid', 0xC7A1D7, NamedColorSource.jis),
  NamedColor('紫紺', 'しこん', 0x402949, NamedColorSource.jis),
  NamedColor('菖蒲色', 'あやめいろ', 0xC27BC8, NamedColorSource.jis),
  NamedColor('牡丹色', 'ぼたんいろ', 0xC24DAE, NamedColorSource.jis),
  NamedColor('マゼンタ', 'magenta', 0xC949A2, NamedColorSource.jis),
  NamedColor('赤紫', 'あかむらさき', 0xC54EA0, NamedColorSource.jis),
  NamedColor('チェリーピンク', 'cherry pink', 0xCF61A5, NamedColorSource.jis),
  NamedColor('躑躅色', 'つつじいろ', 0xCB4B94, NamedColorSource.jis),
  NamedColor('ローズレッド', 'rose red', 0xC74F90, NamedColorSource.jis),
  NamedColor('鴇色', 'ときいろ', 0xF9A1D0, NamedColorSource.jis),
  NamedColor('桜色', 'さくらいろ', 0xFFDBED, NamedColorSource.jis),
  NamedColor('ルビーレッド', 'ruby red', 0xB91E68, NamedColorSource.jis),
  NamedColor('ローズグレイ', 'rose gray', 0x93848B, NamedColorSource.jis),
  NamedColor('コチニールレッド', 'cochineal red', 0xAF3168, NamedColorSource.jis),
  NamedColor('ワインレッド', 'wine red', 0x83274E, NamedColorSource.jis),
  NamedColor('ストロベリー', 'strawberry', 0xBB1E5E, NamedColorSource.jis),
  NamedColor('バーガンディー', 'burgundy', 0x452A35, NamedColorSource.jis),
  NamedColor('胡粉色', 'ごふんいろ', 0xF2E8EC, NamedColorSource.jis),
  NamedColor('ローズピンク', 'rose pink', 0xEF93B6, NamedColorSource.jis),
  NamedColor('ローズ', 'rose', 0xD94177, NamedColorSource.jis),
  NamedColor('薔薇色', 'ばらいろ', 0xD34778, NamedColorSource.jis),
  NamedColor('オールドローズ', 'old rose', 0xC97F96, NamedColorSource.jis),
  NamedColor('唐紅', 'からくれない', 0xE3557F, NamedColorSource.jis),
  NamedColor('紅色', 'くれないいろ/べにいろ', 0xBD1E48, NamedColorSource.jis),
  NamedColor('珊瑚色', 'さんごいろ', 0xFF87A0, NamedColorSource.jis),
  NamedColor('コーラルレッド', 'coral red', 0xFF87A0, NamedColorSource.jis),
  NamedColor('ピンク', 'pink', 0xEB97A8, NamedColorSource.jis),
  NamedColor('紅赤', 'べにあか', 0xB92946, NamedColorSource.jis),
  NamedColor('カーマイン', 'carmine', 0xBE1E3E, NamedColorSource.jis),
  NamedColor('桃色', 'ももいろ', 0xE38698, NamedColorSource.jis),
  NamedColor('紅梅色', 'こうばいいろ', 0xE08899, NamedColorSource.jis),
  NamedColor('ボルドー', 'bordeaux', 0x55353B, NamedColorSource.jis),
  NamedColor('ベビーピンク', 'baby pink', 0xFFC9D2, NamedColorSource.jis),
  NamedColor('シグナルレッド', 'signal red', 0xCE314A, NamedColorSource.jis),
  NamedColor('茜色', 'あかねいろ', 0xA0283A, NamedColorSource.jis),
  NamedColor('ポピーレッド', 'poppy red', 0xDD4157, NamedColorSource.jis),
  NamedColor('赤', 'あか', 0xBF1E33, NamedColorSource.jis),
  NamedColor('臙脂色', 'えんじいろ', 0xAE3846, NamedColorSource.jis),
  NamedColor('蘇芳色', 'すおういろ', 0x974B52, NamedColorSource.jis),
  NamedColor('レッド', 'red', 0xDE424C, NamedColorSource.jis),
  NamedColor('トマトレッド', 'tomato red', 0xDE424C, NamedColorSource.jis),
  NamedColor('マルーン', 'maroon', 0x682A2B, NamedColorSource.jis),
  NamedColor('aliceblue', 'aliceblue', 0xF0F8FF, NamedColorSource.css),
  NamedColor('antiquewhite', 'antiquewhite', 0xFAEBD7, NamedColorSource.css),
  NamedColor('aqua', 'aqua', 0x00FFFF, NamedColorSource.css),
  NamedColor('aquamarine', 'aquamarine', 0x7FFFD4, NamedColorSource.css),
  NamedColor('azure', 'azure', 0xF0FFFF, NamedColorSource.css),
  NamedColor('beige', 'beige', 0xF5F5DC, NamedColorSource.css),
  NamedColor('bisque', 'bisque', 0xFFE4C4, NamedColorSource.css),
  NamedColor('black', 'black', 0x000000, NamedColorSource.css),
  NamedColor('blanchedalmond', 'blanchedalmond', 0xFFEBCD, NamedColorSource.css),
  NamedColor('blue', 'blue', 0x0000FF, NamedColorSource.css),
  NamedColor('blueviolet', 'blueviolet', 0x8A2BE2, NamedColorSource.css),
  NamedColor('brown', 'brown', 0xA52A2A, NamedColorSource.css),
  NamedColor('burlywood', 'burlywood', 0xDEB887, NamedColorSource.css),
  NamedColor('cadetblue', 'cadetblue', 0x5F9EA0, NamedColorSource.css),
  NamedColor('chartreuse', 'chartreuse', 0x7FFF00, NamedColorSource.css),
  NamedColor('chocolate', 'chocolate', 0xD2691E, NamedColorSource.css),
  NamedColor('coral', 'coral', 0xFF7F50, NamedColorSource.css),
  NamedColor('cornflowerblue', 'cornflowerblue', 0x6495ED, NamedColorSource.css),
  NamedColor('cornsilk', 'cornsilk', 0xFFF8DC, NamedColorSource.css),
  NamedColor('crimson', 'crimson', 0xDC143C, NamedColorSource.css),
  NamedColor('cyan', 'cyan', 0x00FFFF, NamedColorSource.css),
  NamedColor('darkblue', 'darkblue', 0x00008B, NamedColorSource.css),
  NamedColor('darkcyan', 'darkcyan', 0x008B8B, NamedColorSource.css),
  NamedColor('darkgoldenrod', 'darkgoldenrod', 0xB8860B, NamedColorSource.css),
  NamedColor('darkgray', 'darkgray', 0xA9A9A9, NamedColorSource.css),
  NamedColor('darkgreen', 'darkgreen', 0x006400, NamedColorSource.css),
  NamedColor('darkgrey', 'darkgrey', 0xA9A9A9, NamedColorSource.css),
  NamedColor('darkkhaki', 'darkkhaki', 0xBDB76B, NamedColorSource.css),
  NamedColor('darkmagenta', 'darkmagenta', 0x8B008B, NamedColorSource.css),
  NamedColor('darkolivegreen', 'darkolivegreen', 0x556B2F, NamedColorSource.css),
  NamedColor('darkorange', 'darkorange', 0xFF8C00, NamedColorSource.css),
  NamedColor('darkorchid', 'darkorchid', 0x9932CC, NamedColorSource.css),
  NamedColor('darkred', 'darkred', 0x8B0000, NamedColorSource.css),
  NamedColor('darksalmon', 'darksalmon', 0xE9967A, NamedColorSource.css),
  NamedColor('darkseagreen', 'darkseagreen', 0x8FBC8F, NamedColorSource.css),
  NamedColor('darkslateblue', 'darkslateblue', 0x483D8B, NamedColorSource.css),
  NamedColor('darkslategray', 'darkslategray', 0x2F4F4F, NamedColorSource.css),
  NamedColor('darkslategrey', 'darkslategrey', 0x2F4F4F, NamedColorSource.css),
  NamedColor('darkturquoise', 'darkturquoise', 0x00CED1, NamedColorSource.css),
  NamedColor('darkviolet', 'darkviolet', 0x9400D3, NamedColorSource.css),
  NamedColor('deeppink', 'deeppink', 0xFF1493, NamedColorSource.css),
  NamedColor('deepskyblue', 'deepskyblue', 0x00BFFF, NamedColorSource.css),
  NamedColor('dimgray', 'dimgray', 0x696969, NamedColorSource.css),
  NamedColor('dimgrey', 'dimgrey', 0x696969, NamedColorSource.css),
  NamedColor('dodgerblue', 'dodgerblue', 0x1E90FF, NamedColorSource.css),
  NamedColor('firebrick', 'firebrick', 0xB22222, NamedColorSource.css),
  NamedColor('floralwhite', 'floralwhite', 0xFFFAF0, NamedColorSource.css),
  NamedColor('forestgreen', 'forestgreen', 0x228B22, NamedColorSource.css),
  NamedColor('fuchsia', 'fuchsia', 0xFF00FF, NamedColorSource.css),
  NamedColor('gainsboro', 'gainsboro', 0xDCDCDC, NamedColorSource.css),
  NamedColor('ghostwhite', 'ghostwhite', 0xF8F8FF, NamedColorSource.css),
  NamedColor('gold', 'gold', 0xFFD700, NamedColorSource.css),
  NamedColor('goldenrod', 'goldenrod', 0xDAA520, NamedColorSource.css),
  NamedColor('gray', 'gray', 0x808080, NamedColorSource.css),
  NamedColor('green', 'green', 0x008000, NamedColorSource.css),
  NamedColor('greenyellow', 'greenyellow', 0xADFF2F, NamedColorSource.css),
  NamedColor('grey', 'grey', 0x808080, NamedColorSource.css),
  NamedColor('honeydew', 'honeydew', 0xF0FFF0, NamedColorSource.css),
  NamedColor('hotpink', 'hotpink', 0xFF69B4, NamedColorSource.css),
  NamedColor('indianred', 'indianred', 0xCD5C5C, NamedColorSource.css),
  NamedColor('indigo', 'indigo', 0x4B0082, NamedColorSource.css),
  NamedColor('ivory', 'ivory', 0xFFFFF0, NamedColorSource.css),
  NamedColor('khaki', 'khaki', 0xF0E68C, NamedColorSource.css),
  NamedColor('lavender', 'lavender', 0xE6E6FA, NamedColorSource.css),
  NamedColor('lavenderblush', 'lavenderblush', 0xFFF0F5, NamedColorSource.css),
  NamedColor('lawngreen', 'lawngreen', 0x7CFC00, NamedColorSource.css),
  NamedColor('lemonchiffon', 'lemonchiffon', 0xFFFACD, NamedColorSource.css),
  NamedColor('lightblue', 'lightblue', 0xADD8E6, NamedColorSource.css),
  NamedColor('lightcoral', 'lightcoral', 0xF08080, NamedColorSource.css),
  NamedColor('lightcyan', 'lightcyan', 0xE0FFFF, NamedColorSource.css),
  NamedColor('lightgoldenrodyellow', 'lightgoldenrodyellow', 0xFAFAD2, NamedColorSource.css),
  NamedColor('lightgray', 'lightgray', 0xD3D3D3, NamedColorSource.css),
  NamedColor('lightgreen', 'lightgreen', 0x90EE90, NamedColorSource.css),
  NamedColor('lightgrey', 'lightgrey', 0xD3D3D3, NamedColorSource.css),
  NamedColor('lightpink', 'lightpink', 0xFFB6C1, NamedColorSource.css),
  NamedColor('lightsalmon', 'lightsalmon', 0xFFA07A, NamedColorSource.css),
  NamedColor('lightseagreen', 'lightseagreen', 0x20B2AA, NamedColorSource.css),
  NamedColor('lightskyblue', 'lightskyblue', 0x87CEFA, NamedColorSource.css),
  NamedColor('lightslategray', 'lightslategray', 0x778899, NamedColorSource.css),
  NamedColor('lightslategrey', 'lightslategrey', 0x778899, NamedColorSource.css),
  NamedColor('lightsteelblue', 'lightsteelblue', 0xB0C4DE, NamedColorSource.css),
  NamedColor('lightyellow', 'lightyellow', 0xFFFFE0, NamedColorSource.css),
  NamedColor('lime', 'lime', 0x00FF00, NamedColorSource.css),
  NamedColor('limegreen', 'limegreen', 0x32CD32, NamedColorSource.css),
  NamedColor('linen', 'linen', 0xFAF0E6, NamedColorSource.css),
  NamedColor('magenta', 'magenta', 0xFF00FF, NamedColorSource.css),
  NamedColor('maroon', 'maroon', 0x800000, NamedColorSource.css),
  NamedColor('mediumaquamarine', 'mediumaquamarine', 0x66CDAA, NamedColorSource.css),
  NamedColor('mediumblue', 'mediumblue', 0x0000CD, NamedColorSource.css),
  NamedColor('mediumorchid', 'mediumorchid', 0xBA55D3, NamedColorSource.css),
  NamedColor('mediumpurple', 'mediumpurple', 0x9370DB, NamedColorSource.css),
  NamedColor('mediumseagreen', 'mediumseagreen', 0x3CB371, NamedColorSource.css),
  NamedColor('mediumslateblue', 'mediumslateblue', 0x7B68EE, NamedColorSource.css),
  NamedColor('mediumspringgreen', 'mediumspringgreen', 0x00FA9A, NamedColorSource.css),
  NamedColor('mediumturquoise', 'mediumturquoise', 0x48D1CC, NamedColorSource.css),
  NamedColor('mediumvioletred', 'mediumvioletred', 0xC71585, NamedColorSource.css),
  NamedColor('midnightblue', 'midnightblue', 0x191970, NamedColorSource.css),
  NamedColor('mintcream', 'mintcream', 0xF5FFFA, NamedColorSource.css),
  NamedColor('mistyrose', 'mistyrose', 0xFFE4E1, NamedColorSource.css),
  NamedColor('moccasin', 'moccasin', 0xFFE4B5, NamedColorSource.css),
  NamedColor('navajowhite', 'navajowhite', 0xFFDEAD, NamedColorSource.css),
  NamedColor('navy', 'navy', 0x000080, NamedColorSource.css),
  NamedColor('oldlace', 'oldlace', 0xFDF5E6, NamedColorSource.css),
  NamedColor('olive', 'olive', 0x808000, NamedColorSource.css),
  NamedColor('olivedrab', 'olivedrab', 0x6B8E23, NamedColorSource.css),
  NamedColor('orange', 'orange', 0xFFA500, NamedColorSource.css),
  NamedColor('orangered', 'orangered', 0xFF4500, NamedColorSource.css),
  NamedColor('orchid', 'orchid', 0xDA70D6, NamedColorSource.css),
  NamedColor('palegoldenrod', 'palegoldenrod', 0xEEE8AA, NamedColorSource.css),
  NamedColor('palegreen', 'palegreen', 0x98FB98, NamedColorSource.css),
  NamedColor('paleturquoise', 'paleturquoise', 0xAFEEEE, NamedColorSource.css),
  NamedColor('palevioletred', 'palevioletred', 0xDB7093, NamedColorSource.css),
  NamedColor('papayawhip', 'papayawhip', 0xFFEFD5, NamedColorSource.css),
  NamedColor('peachpuff', 'peachpuff', 0xFFDAB9, NamedColorSource.css),
  NamedColor('peru', 'peru', 0xCD853F, NamedColorSource.css),
  NamedColor('pink', 'pink', 0xFFC0CB, NamedColorSource.css),
  NamedColor('plum', 'plum', 0xDDA0DD, NamedColorSource.css),
  NamedColor('powderblue', 'powderblue', 0xB0E0E6, NamedColorSource.css),
  NamedColor('purple', 'purple', 0x800080, NamedColorSource.css),
  NamedColor('rebeccapurple', 'rebeccapurple', 0x663399, NamedColorSource.css),
  NamedColor('red', 'red', 0xFF0000, NamedColorSource.css),
  NamedColor('rosybrown', 'rosybrown', 0xBC8F8F, NamedColorSource.css),
  NamedColor('royalblue', 'royalblue', 0x4169E1, NamedColorSource.css),
  NamedColor('saddlebrown', 'saddlebrown', 0x8B4513, NamedColorSource.css),
  NamedColor('salmon', 'salmon', 0xFA8072, NamedColorSource.css),
  NamedColor('sandybrown', 'sandybrown', 0xF4A460, NamedColorSource.css),
  NamedColor('seagreen', 'seagreen', 0x2E8B57, NamedColorSource.css),
  NamedColor('seashell', 'seashell', 0xFFF5EE, NamedColorSource.css),
  NamedColor('sienna', 'sienna', 0xA0522D, NamedColorSource.css),
  NamedColor('silver', 'silver', 0xC0C0C0, NamedColorSource.css),
  NamedColor('skyblue', 'skyblue', 0x87CEEB, NamedColorSource.css),
  NamedColor('slateblue', 'slateblue', 0x6A5ACD, NamedColorSource.css),
  NamedColor('slategray', 'slategray', 0x708090, NamedColorSource.css),
  NamedColor('slategrey', 'slategrey', 0x708090, NamedColorSource.css),
  NamedColor('snow', 'snow', 0xFFFAFA, NamedColorSource.css),
  NamedColor('springgreen', 'springgreen', 0x00FF7F, NamedColorSource.css),
  NamedColor('steelblue', 'steelblue', 0x4682B4, NamedColorSource.css),
  NamedColor('tan', 'tan', 0xD2B48C, NamedColorSource.css),
  NamedColor('teal', 'teal', 0x008080, NamedColorSource.css),
  NamedColor('thistle', 'thistle', 0xD8BFD8, NamedColorSource.css),
  NamedColor('tomato', 'tomato', 0xFF6347, NamedColorSource.css),
  NamedColor('turquoise', 'turquoise', 0x40E0D0, NamedColorSource.css),
  NamedColor('violet', 'violet', 0xEE82EE, NamedColorSource.css),
  NamedColor('wheat', 'wheat', 0xF5DEB3, NamedColorSource.css),
  NamedColor('white', 'white', 0xFFFFFF, NamedColorSource.css),
  NamedColor('whitesmoke', 'whitesmoke', 0xF5F5F5, NamedColorSource.css),
  NamedColor('yellow', 'yellow', 0xFFFF00, NamedColorSource.css),
  NamedColor('yellowgreen', 'yellowgreen', 0x9ACD32, NamedColorSource.css),
];
